### ISSUE TITLE
Redux State: Beings

### ISSUE THREAD

**Issue by M3L6H** [M3L6H/Chaos#15]
**ToDo**

- [x] [`entities/beings`, reducer, actions](https://github.com/M3L6H/Chaos/wiki/Sample-State)

- [x] [`session`, reducer, actions](https://github.com/M3L6H/Chaos/wiki/Sample-State)

- [x] [`errors`, reducer, actions](https://github.com/M3L6H/Chaos/wiki/Sample-State)

**Comment by M3L6H** [comment]
Added the slices of state and their corresponding action creators/reducers
