### ISSUE TITLE
Beings

### ISSUE THREAD

**Issue by M3L6H** [M3L6H/Chaos#2]
**ToDo**

- [x] [`beings` table](https://github.com/M3L6H/Chaos/wiki/Schema#beings)
- [x] [`Being` model](https://github.com/M3L6H/Chaos/wiki/Models#being)
- [x] [`BeingsController`](https://github.com/M3L6H/Chaos/wiki/Controllers#beings_controller)
- [x] Being routes

**Comment by M3L6H** [comment]
Finished beings
